name: CI/CD Pipeline – Novena EHR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build & Push Backend image
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ehr-backend:latest

      # 5️⃣ Build & Push Frontend image
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ehr-frontend:latest

      # 6️⃣ (Optional) Deploy to Kubernetes
      - name: Set up kubectl
        if: ${{ secrets.KUBE_CONFIG }}
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Deploy to Kubernetes Cluster
        if: ${{ secrets.KUBE_CONFIG }}
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBECONFIG_FILE" > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/
